# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "syncserver-ios-test" do

pod 'syncano-ios'
pod 'CrittercismSDK'

end

target "syncserver-ios-testTests" do

end

